const mockData = [
    {
      index: 1,
      url: "https://source.unsplash.com/random/?biryani",
      time: "35 mins",
      item_name: "Biryani",
      provider: "Meghna Foods",
      rating: 4.4,
    },
    {
      index: 2,
      url: "https://source.unsplash.com/random/?paneer",
      time: "30 mins",
      item_name: "Paneer chilli",
      provider: "Santosh Foods",
      rating: 4.5,
    },
    {
      index: 3,
      url: "https://source.unsplash.com/random/?sweets",
      time: "25 mins",
      item_name: "Sweets",
      provider: "Meghna Sweets",
      rating: 3.4,
    },
    {
      index: 4,
      url: "https://source.unsplash.com/random/?rice",
      time: "20 mins",
      item_name: "Daal Chawal",
      provider: "Meghna Foods",
      rating: 4.0,
    },
    {
      index: 5,
      url: "https://source.unsplash.com/random/?shake",
      time: "19 mins",
      item_name: "Banan Shake",
      provider: "twinkle Foods",
      rating: 3.9,
    },
    {
      index: 6,
      url: "https://source.unsplash.com/random/?panipuri",
      time: "20 mins",
      item_name: "Pani Puri",
      provider: "Meghna Foods",
      rating: 4.8,
    },
    {
      index: 7,
      url: "https://source.unsplash.com/random/?halwa",
      time: "2 mins",
      item_name: "Halwa",
      provider: "Dessert Foods",
      rating: 3.9,
    },
    {
      index: 8,
      url: "https://source.unsplash.com/random/?khichri",
      time: "35 mins",
      item_name: "Khichri",
      provider: "Meghna Foods",
      rating: 3.8,
    },
    {
      index: 9,
      url: "https://source.unsplash.com/random/?chicken",
      time: "55 mins",
      item_name: "Chicken",
      provider: "Twinkle Foods",
      rating: 4.8,
    },
    {
      index: 10,
      url: "https://source.unsplash.com/random/?icecream",
      time: "25 mins",
      item_name: "Ice Cream",
      provider: "Dessert Foods",
      rating: 5.0,
    },
    {
      index:11,
      url: "https://source.unsplash.com/random/?biriyani",
      time: "55 mins",
      item_name: "biriyani",
      provider: "Indian Foods",
      rating: 5.0,
    },
    {
      index: 12,
      url: "https://source.unsplash.com/random/?friedrice",
      time: "35 mins",
      item_name: "Fried Rice",
      provider: "Ashoka Foods",
      rating: 4.8,
    },
  ];

  export default mockData;